/**
 * 页面上给人看的字，中英各一份。
 *
 * 两个地方用它：onboard.mjs 里那些回给页面的话（接上了、记下了、报错）直接 import；
 * 页面自己那份由 onboard.mjs 在发 ui/app.html 时把这个文件整段内联进去（替换 // __STRINGS__ 那一行），
 * 所以这里只能写浏览器也认的东西：别 import 别的模块，别碰 node 的 API。
 *
 * core/tools.mjs 里的文本是写给模型看的，一律中文，不进这张表。
 */
export const STRINGS = {
  zh: {
  lang: "English", tabToday: "今天", tabHabits: "习惯", tabHands: "手", tabSettings: "设置",
  title: "设置 shoulder-tap", sub: "五步，都能跳过。之后点托盘图标就回到这里。",
  todayH: "今天要做的事", todayWhy: "一行一件，按顺序。第一行是它盯着的那件。", todayPh: "做作品集\n接着做推理编排\n回邮件",
  todayRewrite: "重写今天的清单", todayReplace: "填了会替换上面这些。", todayEmpty: "今天还没记。", saveList: "保存清单",
  now: "现在", doneBtn: "完成", dropBtn: "今天不做", pendingOpt: "待做", progress: (d, n) => `${d}/${n}`,
  habitsH: "在盯的习惯", historyH: "记录", addHabitH: "加一个", habitsEmpty: "还没有习惯。", historyEmpty: "还没有记录。",
  habitH: "第一个习惯", habitWhy: "名字你定。它在你有停顿时提一句，不打断你。", habitName: "习惯", habitPh: "喝水、健身、站起来走走",
  habitWhen: "什么时候提醒", every: "每隔", min: "分钟", daily: "每天", habitKind: "能不能跳过", addHabit: "加上",
  soft: "软习惯 · 随手就能做", softWhy: "正因为简单，所以不能跳过。到点就提，直到你说做了。喝水这种。",
  hard: "硬习惯 · 看当天情况", hardWhy: "可以说「今天不做」，给个原因，今天不再提。健身这种。",
  softTag: "软", hardTag: "硬", everyTxt: (m) => `每 ${m} 分钟`, atTxt: (a) => `每天 ${a}`, dueTxt: (m) => `超了 ${m} 分钟`,
  logBtn: "做了", skipBtn: "今天不做", skipWhy: "为什么今天不做？", stopped: "停用",
  tryTap: "在屏幕上试一下", tryTapWhy: "到点时它就这样拍你。", tapSample: (n) => `${n} —— 该做了`,
  handsH: "手的设置", handsWhy: "点一下预览台看动作。「桌面上试」是真的拍。",
  gTap: "跑偏了 / 习惯到点", gPat: "模型在等你回答", gSnap: "这轮做完了", tryDesk: "桌面上试",
  tapText: "喝水 —— 45 分钟没动了", patText: "这条算完成了吗？", snapText: "做完了：README 加了卸载那节",
  styleH: "样式", styleHint: "想加一套：在 ui/sprites/skins/ 下建个文件夹，放 tap.png、pat.png、snap.png（各 864×80，9 帧）。", inUse: "在用", switched: "换好了，下次拍就是它。",
  updateAvail: (n) => `shoulder-tap 有新版本（新了 ${n} 个提交）。`, updateBtn: "更新",
  showH: "停留时间", showWhy: "手和那句话在屏幕上停多久。", secs: (n) => `${n} 秒`,
  noDesktop: "这台机器没装桌面端，拍肩只落在聊天里。",
  connectH: "编程工具", connectWhy: "让 Claude Code / Codex 看到你今天要做的事。都在这台机器上跑。",
  connectMore: "自己动手，或交给模型", connectCmd: "终端里跑：", connectCodex: "Codex：加进 ~/.codex/config.toml", connectAgent: "或把这段发给你的 coding agent：", copy: "复制",
  desktopNote: "只有工具，没有钩子：不会自己拦你、拍你", connected: "已接上", remote: "接的是旧的远程版", installed: "装了，还没接", missing: "没找到", btnSwap: "换成本机版", btnConnect: "接上", connecting: "接着……",
  copied: "复制好了。", copyFail: "浏览器不让复制，手动选中吧。",
  storageH: "数据放哪", promise: "你的所有习惯 + 要做的事情的数据不上云。", promiseWhy: "shoulder-tap 没有服务器。数据在这台机器上，或在你自己的 Notion 里。",
  local: "这台机器", localWhy: "一个 JSON 文件，不用配。只在这一台上有。", notion: "我自己的 Notion", notionWhy: "手机上也能看。这台机器直连你的 Notion。",
  ntoken: "Notion integration 密钥（ntn_ 开头）", npage: "一个 Notion 页面的链接",
  n1: "密钥在 notion.so/profile/integrations 新建一个 integration 拿。", n2: "那个页面右上角 ⋯ → Connections → 加上它。", n3: "已经记在本地的习惯和今天的事会一起搬过去。",
  needBoth: "密钥和页面链接都要填。", saving: "保存中……", save: "保存",
  uninstall: "卸载（数据留着；加 --purge 一起删）：", backHome: "← 回到首页",
  goSetup: "重新走一遍设置", goSetupFirst: "开始设置", goSetupWhy: "编程工具、习惯、今天的事、数据放哪", goHands: "手的设置", goHandsWhy: "预览手势、换样式、停留时间",
  tasksH: "待办", todayLabel: "今天", notDone: "没做完",
  agentHintH: "也可以直接跟 Claude Code / Codex 说：", agentSays: ["加一条：回邮件", "第 2 条今天不做了", "喝完水了", "每天 22:30 提醒我健身"],
  tryH: "试一下", tryWhy: "都在你平时用的对话框里说，不用记命令。",
  try1: "重开一次 Claude Code（新会话才看得到 shoulder-tap）。",
  try2: "告诉它今天要做什么：", try2Say: "今天要做：写周报，回邮件", try2Then: "它会记下来，按顺序盯着第一件。",
  try3: "再说一件不相干的事：", try3Say: "帮我查一下明天的天气", try3Then: "它照样回答，但很短；结尾有只手，屏幕右边也会拍你一下。",
  try4: "做完一个习惯就说一声：", try4Say: "喝完水了", try4Then: "它记一笔，下次到点再提。",
  back: "上一步", skip: "跳过", next: "下一步", finish: "完成", fail: "没成功", welcome: "设置好了。以后点托盘图标就回到这里。",
  gone: "这个页面断开了。", goneWhy: "页面关着一阵后后台会自己停。点一下托盘 / 菜单栏图标，就会开一个新的。",
  agentMd: (m) => [
    "# 帮我接上 shoulder-tap 的 MCP（本机 stdio，不经过服务器）", "",
    "Claude Code：", "", "```bash", m.command, "```", "",
    "Codex：加进 ~/.codex/config.toml（已有 [mcp_servers.shoulder-tap] 就替换）", "", "```toml", m.codexBlock, "```", "",
    "OpenClaw（装了的话）：", "", "```bash", m.openclawCommand, "```", "",
    "Hermes（装了的话）：加进 ~/.hermes/config.yaml 的 mcp_servers 下面", "", "```yaml", m.hermesBlock, "```", "",
    "接完用 `claude mcp get shoulder-tap` 确认是 stdio、Connected，然后打开设置页让我填剩下的：", "",
    "```bash", `node ${JSON.stringify(m.onboard)} --setup`, "```", "", "最后提醒我重开一次会话。",
  ].join("\n"),
    // —— 下面这些是服务端回给页面的话 ——
    claude: "Claude Code 接上了。已经开着的会话要重开一次才看得到新工具。",
    codex: "Codex 接上了（写进了 ~/.codex/config.toml）。重开一次 Codex 生效。",
    desktop: "Claude Desktop 接上了。完全退出它（托盘图标右键 Quit）再打开才生效。它没有钩子：不会自己拦你、拍你，你让它查清单、记习惯时才调工具。",
    unknownClient: "不认识的客户端",
    openclaw: "OpenClaw 接上了（openclaw mcp add）。开一个新会话生效。它没有钩子：你让它查清单、记习惯时才调工具。",
    hermes: "Hermes 接上了（写进了 ~/.hermes/config.yaml）。重开 Hermes 或在里面打 /reload-mcp 生效。它没有钩子：你让它查清单、记习惯时才调工具。",
    noDesktopApp: "这台机器上没找到 Claude Desktop",
    addFailed: "mcp add 失败",
    badToken: "这不像 Notion integration 的密钥（应该是 ntn_ 开头）",
    notionSays: (e) => `Notion 说：${e.message}（code: ${e.code}）`,
    adopted: (title, added) => `接管了你已有的库「${title}」` + (added.length ? `，补上了：${added.join("、")}` : "，字段本来就齐"),
    created: (where) => `建好了：${where}`,
    moved: (xs) => `\n搬到 Notion 的：${xs.join("、")}`,
    movedTasks: (n) => `今天的 ${n} 件事`,
    localData: (p) => `就放在这台机器上：${p}`,
    saved: "好了。",
    needWhen: "得说清楚：隔多久一次，还是每天几点。",
    habitAdded: (h) => `加上了：${h.name}，${h.at ? `每天 ${h.at}` : `每 ${h.everyMin} 分钟`}（${h.kind === "soft" ? "软" : "硬"}）。`,
    noHabit: (n) => `没找到「${n}」。`,
    refused: (n) => `「${n}」是软习惯，随手就能做的事不能跳过。什么都没记，到点照样会提醒。`,
    skipped: (n) => `记下了：${n} 今天跳过。`,
    logged: (h) => `记下了：${h.name}，下次提醒${h.at ? `明天 ${h.at}` : `在 ${h.everyMin} 分钟后`}。`,
    badGesture: (g) => `没有这种手势：${g}`,
    badMotion: (m) => `motion 只能是 system 或 always：${m}`,
    badSkin: (s) => `没有这套皮肤：${s}`,
    badShowSec: (n) => `停留时间要在 3 到 60 秒之间：${n}`,
    badStatus: (s) => `没有这种状态：${s}`,
    noTask: "没找到这一条，可能刚被别处改过。刷新一下。",
    updating: "在更新了，大概一分钟。桌面端会重启一下，这一页断开后点托盘 / 菜单栏图标重新打开就是新版。",
    noRepo: "找不到装的时候那个 git 仓库。重新 git clone 再跑 node install.mjs，以后就能在这里更新。",
    showSaved: (n) => `好了，之后每次停 ${n} 秒。`,
    tryOnce: "试一下",
  },
  en: {
  lang: "中文", tabToday: "Today", tabHabits: "Habits", tabHands: "Hand", tabSettings: "Settings",
  title: "Set up shoulder-tap", sub: "Five steps, all skippable. Click the tray icon to come back here.",
  todayH: "Today", todayWhy: "One per line, in order. The first is the one it watches.", todayPh: "portfolio\ninference orchestration\nreply to email",
  todayRewrite: "Rewrite today's list", todayReplace: "Saving replaces the list above.", todayEmpty: "Nothing for today yet.", saveList: "Save list",
  now: "now", doneBtn: "Done", dropBtn: "Not today", pendingOpt: "To do", progress: (d, n) => `${d}/${n}`,
  habitsH: "Habits", historyH: "History", addHabitH: "Add one", habitsEmpty: "No habits yet.", historyEmpty: "Nothing logged yet.",
  habitH: "First habit", habitWhy: "Any name. It nudges you at a pause, never mid-task.", habitName: "Habit", habitPh: "drink water, workout, stand up",
  habitWhen: "When to remind", every: "Every", min: "min", daily: "Daily at", habitKind: "Can it be skipped?", addHabit: "Add",
  soft: "Soft · quick to do", softWhy: "Simple, so no skipping. Reminds until you say done. Drinking water.",
  hard: "Hard · depends on the day", hardWhy: "You can say “not today” with a reason. Workout.",
  softTag: "soft", hardTag: "hard", everyTxt: (m) => `every ${m} min`, atTxt: (a) => `daily ${a}`, dueTxt: (m) => `${m} min overdue`,
  logBtn: "Did it", skipBtn: "Not today", skipWhy: "Why not today?", stopped: "stopped",
  tryTap: "Try it on screen", tryTapWhy: "This is how it taps you when it's due.", tapSample: (n) => `${n} — time`,
  handsH: "Hand settings", handsWhy: "Click a stage to play. “Try on desktop” really taps.",
  gTap: "drifted / habit due", gPat: "model is waiting for you", gSnap: "turn finished", tryDesk: "Try on desktop",
  tapText: "Drink water — 45 min overdue", patText: "Is this one done?", snapText: "Done: README got an uninstall section",
  styleH: "Style", styleHint: "To add one: make a folder under ui/sprites/skins/ with tap.png, pat.png, snap.png (864×80, 9 frames each).", inUse: "in use", switched: "Switched. Next tap uses it.",
  updateAvail: (n) => `A new shoulder-tap is out (${n} commit${n > 1 ? "s" : ""} ahead).`, updateBtn: "Update",
  showH: "How long it stays", showWhy: "How long the hand and its line stay on screen.", secs: (n) => `${n} s`,
  noDesktop: "No desktop app on this machine; taps land in the chat only.",
  connectH: "Coding tools", connectWhy: "So Claude Code / Codex can see what you're doing today. Everything runs on this machine.",
  connectMore: "Do it yourself, or hand it to the model", connectCmd: "In a terminal:", connectCodex: "Codex: add to ~/.codex/config.toml", connectAgent: "Or paste this to your coding agent:", copy: "Copy",
  desktopNote: "tools only, no hooks: it won't stop you or tap on its own", connected: "Connected", remote: "Points at the old remote version", installed: "Installed, not connected", missing: "Not found", btnSwap: "Switch to local", btnConnect: "Connect", connecting: "Connecting…",
  copied: "Copied.", copyFail: "Clipboard blocked. Select it by hand.",
  storageH: "Where data lives", promise: "Your habits and tasks never leave your machine.", promiseWhy: "shoulder-tap has no server. Data stays on this machine or in your own Notion.",
  local: "This machine", localWhy: "One JSON file, nothing to configure. This computer only.", notion: "My own Notion", notionWhy: "Visible on your phone. This machine talks to Notion directly.",
  ntoken: "Notion integration token (starts with ntn_)", npage: "Link to a Notion page",
  n1: "Create an integration at notion.so/profile/integrations to get the token.", n2: "On that page: ⋯ → Connections → add it.", n3: "Habits and tasks already saved locally move over too.",
  needBoth: "Both token and page link are needed.", saving: "Saving…", save: "Save",
  uninstall: "Uninstall (keeps data; add --purge to delete it): ", backHome: "← Back",
  goSetup: "Run setup again", goSetupFirst: "Start setup", goSetupWhy: "Coding tools, habits, today, where data lives", goHands: "Hand settings", goHandsWhy: "Preview gestures, style, how long it stays",
  tasksH: "Tasks", todayLabel: "Today", notDone: "not done",
  agentHintH: "Or just tell Claude Code / Codex:", agentSays: ["add: reply to email", "skip #2 today", "just drank water", "remind me to work out at 22:30"],
  tryH: "Try it", tryWhy: "Just talk in the chat you already use. No commands to remember.",
  try1: "Restart Claude Code (a new session picks up shoulder-tap).",
  try2: "Tell it what you're doing today:", try2Say: "Today: write the weekly report, reply to email", try2Then: "It saves the list and watches the first item.",
  try3: "Then ask for something unrelated:", try3Say: "What's the weather tomorrow?", try3Then: "It still answers, briefly. A hand ends the reply and taps your screen's right edge.",
  try4: "When you do a habit, say so:", try4Say: "Just drank water", try4Then: "It logs it and reminds you again when it's due.",
  back: "Back", skip: "Skip", next: "Next", finish: "Finish", fail: "Failed", welcome: "All set. Click the tray icon to come back here.",
  gone: "This page lost its connection.", goneWhy: "The background service stops a while after the page goes idle. Click the tray / menu bar icon to open a fresh one.",
  agentMd: (m) => [
    "# Connect the shoulder-tap MCP for me (local stdio, no server)", "",
    "Claude Code:", "", "```bash", m.command, "```", "",
    "Codex: add to ~/.codex/config.toml (replace an existing [mcp_servers.shoulder-tap]):", "", "```toml", m.codexBlock, "```", "",
    "OpenClaw (if installed):", "", "```bash", m.openclawCommand, "```", "",
    "Hermes (if installed): add under mcp_servers in ~/.hermes/config.yaml", "", "```yaml", m.hermesBlock, "```", "",
    "Then confirm with `claude mcp get shoulder-tap` (stdio, Connected) and open the settings page so I can fill in the rest:", "",
    "```bash", `node ${JSON.stringify(m.onboard)} --setup`, "```", "", "Finally remind me to restart the session.",
  ].join("\n"),
    // —— 下面这些是服务端回给页面的话 ——
    claude: "Claude Code is connected. Restart any open session to see the new tools.",
    codex: "Codex is connected (written to ~/.codex/config.toml). Restart Codex for it to take effect.",
    desktop: "Claude Desktop is connected. Quit it completely (tray icon → Quit) and reopen it. It has no hooks: it won't stop you or tap you on its own — it runs the tools when you ask.",
    unknownClient: "Unknown client",
    openclaw: "OpenClaw is connected (openclaw mcp add). Start a new session for it to take effect. It has no hooks: it runs the tools when you ask.",
    hermes: "Hermes is connected (written to ~/.hermes/config.yaml). Restart Hermes or type /reload-mcp in it. It has no hooks: it runs the tools when you ask.",
    noDesktopApp: "Claude Desktop isn't installed on this machine",
    addFailed: "mcp add failed",
    badToken: "That doesn't look like a Notion integration token (it should start with ntn_)",
    notionSays: (e) => `Notion says: ${e.message} (code: ${e.code})`,
    adopted: (title, added) => `Adopted your existing database “${title}”` + (added.length ? `, added: ${added.join(", ")}` : ", the fields were already there"),
    created: (where) => `Created: ${where}`,
    moved: (xs) => `\nMoved to Notion: ${xs.join(", ")}`,
    movedTasks: (n) => `today's ${n} task${n > 1 ? "s" : ""}`,
    localData: (p) => `Stays on this machine: ${p}`,
    saved: "Done.",
    needWhen: "Pick one: every N minutes, or a time of day.",
    habitAdded: (h) => `Added: ${h.name}, ${h.at ? `daily ${h.at}` : `every ${h.everyMin} min`} (${h.kind === "soft" ? "soft" : "hard"}).`,
    noHabit: (n) => `No habit called “${n}”.`,
    refused: (n) => `“${n}” is a soft habit — quick things can't be skipped. Nothing was logged; it will remind you again when it's due.`,
    skipped: (n) => `Logged: ${n} skipped today.`,
    logged: (h) => `Logged: ${h.name}. Next reminder ${h.at ? `tomorrow ${h.at}` : `in ${h.everyMin} min`}.`,
    badGesture: (g) => `No such gesture: ${g}`,
    badMotion: (m) => `motion must be system or always: ${m}`,
    badSkin: (s) => `No such skin: ${s}`,
    badShowSec: (n) => `Must be between 3 and 60 seconds: ${n}`,
    badStatus: (s) => `No such status: ${s}`,
    noTask: "Couldn't find that task; it may have just changed elsewhere. Refresh.",
    updating: "Updating, about a minute. The desktop app restarts; when this page disconnects, click the tray / menu bar icon to reopen it on the new version.",
    noRepo: "Can't find the git checkout it was installed from. git clone it again and run node install.mjs; after that you can update here.",
    showSaved: (n) => `Done. It stays ${n} s from now on.`,
    tryOnce: "try it",
  },
};
